default:
    trainer: ppo
    batch_size: 2048
    beta: 5.0e-3
    buffer_size: 20480
    epsilon: 0.2
    gamma: 0.995
    hidden_units: 512
    lambd: 0.95
    learning_rate: 3.0e-4
    max_steps: 1e6
    memory_size: 256
    normalize: true
    num_epoch: 3
    num_layers: 3
    time_horizon: 1000
    sequence_length: 64
    summary_freq: 1000
    use_recurrent: false
    use_curiosity: false
    curiosity_strength: 0.01
    curiosity_enc_size: 128

BipedRobotLearning:
    normalize: true
    num_epoch: 3
    time_horizon: 1000
    batch_size: 2048
    buffer_size: 20480
    gamma: 0.995
    max_steps: 2e6
    summary_freq: 3000
    num_layers: 3
    hidden_units: 512
    
Controller004WalkerBrain:
    beta: 1.0e-2
    # learning_rate: 1.0e-3
    time_horizon: 128
    summary_freq: 1000
    normalize: true
    num_layers: 2
    hidden_units: 90
    batch_size: 2048
    buffer_size: 10240
    max_steps: 100e5

def-old:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.2
    gamma: 0.99
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    max_steps: 5.0e4
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 1000
    use_recurrent: false
    use_curiosity: false
    curiosity_strength: 0.01
    curiosity_enc_size: 128
